spring.application.name=api-cafeSoluble
server.port=8080


#postgres

spring.datasource.url=jdbc:postgresql://localhost:5432/CafeSolubleDB
spring.datasource.username=postgres
spring.datasource.password=filito
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect